#Author: Sonny Chen
import turtle
turtle.bgcolor("sky blue")

pen = turtle.Turtle()
pen.pensize(2)      #Changes the width of the pen
pen.color("white")
pen.hideturtle()    #This hides the cursor
pen.speed(0)

weather = turtle.textinput("Weather", "Enter Sunny, Cloudy, Rainy, or Snowy:").strip().lower()

circleSize = turtle.window_width()//5

if weather == "sunny":
    pen.up()
    pen.setpos(0, -circleSize//2)
    pen.down()
    pen.color("gold")
    pen.begin_fill()
    pen.circle(circleSize//2)
    pen.end_fill()

elif weather == "cloudy":
    pen.up()
    pen.setpos(circleSize//3,circleSize//4.5)
    pen.down()
    pen.color("gold")
    pen.begin_fill()
    pen.circle(circleSize//3)
    pen.end_fill()

    pen.up()
    pen.setpos(0,-circleSize//3)
    pen.down()
    pen.color("light cyan")
    pen.begin_fill()
    pen.circle(circleSize//3)
    pen.end_fill()

    pen.up()
    pen.setpos(circleSize//3,-circleSize//4)
    pen.down()
    pen.color("light cyan")
    pen.begin_fill()
    pen.circle(circleSize//3)
    pen.end_fill()

    pen.up()
    pen.setpos(-circleSize//3,-circleSize//4)
    pen.down()
    pen.color("light cyan")
    pen.begin_fill()
    pen.circle(circleSize//3)
    pen.end_fill()

    pen.up()
    pen.setpos(-circleSize//12,circleSize//10)
    pen.down()
    pen.color("light cyan")
    pen.begin_fill()
    pen.circle(circleSize//3)
    pen.end_fill()


elif weather == "rainy":
    pen.up()
    pen.setpos(0,-circleSize//3+circleSize//2)
    pen.down()
    pen.color("royal blue")
    pen.begin_fill()
    pen.circle(circleSize//3)
    pen.end_fill()

    pen.up()
    pen.setpos(circleSize//3,-circleSize//4+circleSize//2)
    pen.down()
    pen.color("royal blue")
    pen.begin_fill()
    pen.circle(circleSize//3)
    pen.end_fill()

    pen.up()
    pen.setpos(-circleSize//3,-circleSize//4+circleSize//2)
    pen.down()
    pen.color("royal blue")
    pen.begin_fill()
    pen.circle(circleSize//3)
    pen.end_fill()

    pen.up()
    pen.setpos(-circleSize//15,circleSize//12+circleSize//3)
    pen.down()
    pen.color("royal blue")
    pen.begin_fill()
    pen.circle(circleSize//3)
    pen.end_fill()

    pen.up()
    pen.setpos(-circleSize//15,-circleSize//12)
    pen.down()
    pen.color("royal blue")
    pen.begin_fill()
    pen.circle(circleSize//15)
    pen.end_fill()

    pen.up()
    pen.setpos(0,-circleSize//3)
    pen.down()
    pen.color("royal blue")
    pen.begin_fill()
    pen.circle(circleSize//15)
    pen.end_fill()

    pen.up()
    pen.setpos(circleSize//3,-circleSize//4)
    pen.down()
    pen.color("royal blue")
    pen.begin_fill()
    pen.circle(circleSize//15)
    pen.end_fill()

    pen.up()
    pen.setpos(-circleSize//3,-circleSize//4)
    pen.down()
    pen.color("royal blue")
    pen.begin_fill()
    pen.circle(circleSize//15)
    pen.end_fill()

    pen.up()
    pen.setpos(circleSize//1.5,-circleSize//2.5)
    pen.down()
    pen.color("royal blue")
    pen.begin_fill()
    pen.circle(circleSize//15)
    pen.end_fill()

    pen.up()
    pen.setpos(circleSize//5,-circleSize//2)
    pen.down()
    pen.color("royal blue")
    pen.begin_fill()
    pen.circle(circleSize//15)
    pen.end_fill()

    pen.up()
    pen.setpos(-circleSize//2,-circleSize//4+circleSize//4)
    pen.down()
    pen.color("royal blue")
    pen.begin_fill()
    pen.circle(circleSize//15)
    pen.end_fill()

    pen.up()
    pen.setpos(-circleSize//1.8,-circleSize//3)
    pen.down()
    pen.color("royal blue")
    pen.begin_fill()
    pen.circle(circleSize//15)
    pen.end_fill()

    pen.up()
    pen.setpos(-circleSize//2,-circleSize//4-circleSize//2.5)
    pen.down()
    pen.color("royal blue")
    pen.begin_fill()
    pen.circle(circleSize//15)
    pen.end_fill()

    pen.up()
    pen.setpos(circleSize//3,-circleSize//1.2)
    pen.down()
    pen.color("royal blue")
    pen.begin_fill()
    pen.circle(circleSize//15)
    pen.end_fill()

    pen.up()
    pen.setpos(circleSize//50,-circleSize//1.5)
    pen.down()
    pen.color("royal blue")
    pen.begin_fill()
    pen.circle(circleSize//15)
    pen.end_fill()


elif weather == "snowy":
    pen.up()
    pen.setpos(0,-circleSize//3+circleSize//2)
    pen.down()
    pen.color("white")
    pen.begin_fill()
    pen.circle(circleSize//2.5)
    pen.end_fill()

    pen.up()
    pen.setpos(circleSize//3,-circleSize//4+circleSize//2)
    pen.down()
    pen.color("white")
    pen.begin_fill()
    pen.circle(circleSize//2.5)
    pen.end_fill()

    pen.up()
    pen.setpos(-circleSize//3,-circleSize//4+circleSize//2)
    pen.down()
    pen.color("white")
    pen.begin_fill()
    pen.circle(circleSize//2.5)
    pen.end_fill()

    pen.up()
    pen.setpos(-circleSize//15,circleSize//12+circleSize//3)
    pen.down()
    pen.color("white")
    pen.begin_fill()
    pen.circle(circleSize//2.5)
    pen.end_fill()

    pen.up()
    pen.setpos(-circleSize//15,-circleSize//12)
    pen.down()
    pen.color("white")
    pen.begin_fill()
    pen.circle(circleSize//12)
    pen.end_fill()

    pen.up()
    pen.setpos(0,-circleSize//3)
    pen.down()
    pen.color("white")
    pen.begin_fill()
    pen.circle(circleSize//12)
    pen.end_fill()

    pen.up()
    pen.setpos(circleSize//3,-circleSize//4)
    pen.down()
    pen.color("white")
    pen.begin_fill()
    pen.circle(circleSize//12)
    pen.end_fill()

    pen.up()
    pen.setpos(-circleSize//3,-circleSize//4)
    pen.down()
    pen.color("white")
    pen.begin_fill()
    pen.circle(circleSize//12)
    pen.end_fill()

    pen.up()
    pen.setpos(circleSize//1.5,-circleSize//2.5)
    pen.down()
    pen.color("white")
    pen.begin_fill()
    pen.circle(circleSize//12)
    pen.end_fill()

    pen.up()
    pen.setpos(circleSize//5,-circleSize//2)
    pen.down()
    pen.color("white")
    pen.begin_fill()
    pen.circle(circleSize//12)
    pen.end_fill()

    pen.up()
    pen.setpos(-circleSize//2,-circleSize//4+circleSize//4)
    pen.down()
    pen.color("white")
    pen.begin_fill()
    pen.circle(circleSize//12)
    pen.end_fill()

    pen.up()
    pen.setpos(-circleSize//1.8,-circleSize//3)
    pen.down()
    pen.color("white")
    pen.begin_fill()
    pen.circle(circleSize//12)
    pen.end_fill()

    pen.up()
    pen.setpos(-circleSize//2,-circleSize//4-circleSize//2.5)
    pen.down()
    pen.color("white")
    pen.begin_fill()
    pen.circle(circleSize//12)
    pen.end_fill()

    pen.up()
    pen.setpos(circleSize//3,-circleSize//1.2)
    pen.down()
    pen.color("white")
    pen.begin_fill()
    pen.circle(circleSize//12)
    pen.end_fill()

    pen.up()
    pen.setpos(circleSize//50,-circleSize//1.5)
    pen.down()
    pen.color("white")
    pen.begin_fill()
    pen.circle(circleSize//12)
    pen.end_fill()


turtle.done()